### ISSUE TITLE
icosium + hoggar : optin form

### ISSUE THREAD

**Issue by osminosm** [ioprodz/ioprodz#19]
# Description
We want to gather emails from the landing page, in order to send emails when the registration is open on the platform

# Acceptance
- backend should expose a POST /optins that receives the payload :
````json
{
  "email": "example@example.com", // mandatory
  "source": "discord"  // optional
}

````
- backend should send error if : 
   - email field is not sent or not valid
   - email already exists in data base
- should store unique emails on DB (optin table)
- should not require auth
- should have google recaptcha ( to prevent bots sending fake emails)
- should have form validation (email field)
- should display message that the email has been sent (or server error) -> clears the field.

**Comment by badido39** [comment]
@osminosm  should we have to add validator Lib in the backend or just the validation in frontEnd side ?????

**Comment by osminosm** [comment]
> @osminosm should we have to add validator Lib in the backend or just the validation in frontEnd side ?????

there should be validation server side, do you prefer any library ? Joi , Yup ?

**Comment by badido39** [comment]
I will see wich one i use , i already used Yup with next-js , the lib weight is very important now ...
