### ISSUE TITLE
repo documentation

### ISSUE THREAD

**Issue by osminosm** [ioprodz/ioprodz#3]
Create minimal documentation for the repo

Elements needed:

- description
- pre-required tools
- running the project locally
- how to contribute

**Comment by nazimboudeffa** [comment]
Do we have some documentation about the technologies we're going to use like React and Express or we're going to tell the memebres to stay procrastinate with tutorials on YT without going ahead on the project

**Comment by osminosm** [comment]
> Do we have some documentation about the technologies we're going to use like React and Express or we're going to tell the memebres to stay procrastinate with tutorials on YT without going ahead on the project

We will include documentation about how to use the tools for developing on different projects.

**Comment by nazimboudeffa** [comment]
I agree with the fact that we must use issues before coding a new feature

**Comment by nazimboudeffa** [comment]
I wish if we have a good tutorial about React to let everyone share the same reference and not only procrastinate on YT looking for improving our skills

**Comment by badido39** [comment]
after the discription ofcourse its the roadMap , we have to do choises ==>
1st - wich  ORM to use .(Prisma is in Top 2022)
2nd -wich CSS framework- (i used to integrate MIU material UI is the best for me),
