### ISSUE TITLE
auth : from github and session (part 1)

### ISSUE THREAD

**Issue by osminosm** [ioprodz/ioprodz#31]
# Description 
we need to be able to identify users, and give them a space in app to interact with the platform
we will use github authentication because all our users will be contributing to code projects during their mentoring

### why not email/password : 
because we will have many things covered for us:
- email verification flow
- forgot password  flow
- upload of a profile picture
- the users will not have to fill a form, makes it easier to create an account

# acceptance criteria
- provide an endpoint to launch the authentication flow
- user will agree to allow ioprodz to authenticate him and get his profile
- user is generated a tokens (jwt), set to cookies on the users device
- cookies should be 
  - secured scoped to ioprodz.com 
  - https only
- the two tokens are :
  - access token (TTL 5min) containing : sub <user uuid>, email, scopes <array of scopes> (with other jwt values)
  - refresh token (TTL 24h) containing : sub <user uuid>, tokenId <token uuid>

# tech spec
## routes 
`GET /auth/github`
will start the auth process with github
`POST /auth/github/callback`
will get the confirmation of github
`POST /auth/refresh`
will create a session token, and send now auth tokens

## controllers
- 1 :  receive the auth request and pass it to githubAuthStrategy.authenticate()
- 2 : process the github callback
  - if user profile (by provider id) does not exist , create him one, if not update his profile with new data
  - create a session for him, (should be by device) (yes we store the User-Agent in the session)
  - send him an access token and a refresh (session) token
  
docs: https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#web-application-flow

- 3 : process refresh token
  - decode token, update session.lastusedAt in db (if fail : send 401)
  - send him an access token

## business
```ts
interface AuthStrategy {
   authenticate()
   handleAuthentication()
}
```

```ts
class GithubAuthStrategy implements AuthStrategy {
   // implementation
}
```

```ts
class JwtAuthStrategy implements AuthStrategy {
   // implementation
}
```
## storage

- we keep 3 set of information :
  - identity will contain : id, email, provider <name of authority ex: github>, 
  - profile : id, identityId, name, dob, <we will explore what github gives>, avatarUrl
  - sessions: id, ttl: <int seconds of validity , startedAt<date>, lastusedAt <date>

**Comment by badido39** [comment]
I liked (Part1)
